development:
  clients:
    default:
      database: tap2go
      hosts:
        - localhost:27017
      options:
  options:
    log_level: :debug
production:
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] %>
