development:
  access_key_id: AKIAVCCO3L2J6HBFS2G2
  secret_access_key: 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
test:
  access_key_id: AKIAVCCO3L2J6HBFS2G2
  secret_access_key: 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
production:
  access_key_id: AKIAVCCO3L2J6HBFS2G2
  secret_access_key: 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
